version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: app-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy_to_aws-s3:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python3-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            yarn install
            yarn run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build successfull"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_to_aws-s3
